In [1]:
import numpy as np

# Čia galite naudoti numpy funkcijas ir metodus


In [2]:
vektorius = np.arange(1, 10)

In [3]:
vektorius

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
nulis = np.zeros((10,10))

In [5]:
nulis


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
vienas = np.one(10)

AttributeError: module 'numpy' has no attribute 'one'

In [7]:
vienetai -np.zeros(1)

NameError: name 'vienetai' is not defined

In [8]:
vienetai -np.zeros((1))

NameError: name 'vienetai' is not defined

In [9]:
    vienetai = np.zeros(1)

In [10]:
vienetai

array([0.])

In [11]:
vienas = np.oness(10)

AttributeError: module 'numpy' has no attribute 'oness'

In [12]:
vienas = np.ones(10)

In [13]:
vienas

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
keturi = np.full(10, 4)


In [15]:
keturi

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [16]:
v = = np.full(10, 1)

SyntaxError: invalid syntax (1587773834.py, line 1)

In [17]:
v = = np.full(10, 5)

SyntaxError: invalid syntax (829499385.py, line 1)

In [18]:
v

NameError: name 'v' is not defined

In [19]:
v = np.full(10, 1)

In [20]:
v

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
o = np.full(10, 0)

In [22]:
o

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
y = np.sevens(10)

AttributeError: module 'numpy' has no attribute 'sevens'

In [24]:
nulis = np.zeros((10.2,10))

TypeError: 'float' object cannot be interpreted as an integer

In [26]:
vienass = np.ones(10.3)

TypeError: expected a sequence of integers or a single integer, got '10.3'

In [27]:
vienass = np.ones(10.3)

TypeError: expected a sequence of integers or a single integer, got '10.3'

In [28]:
vienass = np.full(10.3)

TypeError: full() missing 1 required positional argument: 'fill_value'

In [29]:
vienass = np.full(10.3)


TypeError: full() missing 1 required positional argument: 'fill_value'

In [30]:
vienass = np.fulls(10.3)

AttributeError: module 'numpy' has no attribute 'fulls'

In [31]:
vektorius = np.full(10, 4.5)

In [32]:
vektorius

array([4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5])

In [33]:

vektorius = np.arange(0, 101, 2)

In [34]:
vektorius

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [35]:
matrica = np.arange(1, 26).reshape(5, 5)


In [36]:
matrica

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [37]:
skaicius = matrica[2, 1]


In [38]:
skaicius

12

In [39]:
paskutine_eilute = matrica[-1, :]


In [40]:
paskutine_eilute

array([21, 22, 23, 24, 25])

In [41]:
submatrica = matrica[1:4, 1:4]


In [42]:
submatrica

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [43]:
submatrica = matrica[0:3, 0:3]


In [44]:
submatrica

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])